openapi: 3.0.3
info:
  title: Tâches API
  version: 1.0.0
  description: API permettant de gérer des tâches (création, consultation, suppression)

paths:
  /tasks:
    get:
      summary: Obtenir toutes les tâches
      responses:
        '200':
          description: Liste de toutes les tâches existantes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Ajouter plusieurs tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tâches créées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    delete:
      summary: Supprimer plusieurs tâches à partir d'une liste d'identifiants
      requestBody:
